# Generated by Django 5.2.4 on 2025-07-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0003_spiralassessmentresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenthistory',
            options={'ordering': ['date_taken']},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='spiralassessmentresult',
            options={'ordering': ['created_at']},
        ),
    ]
