# Generated by Django 5.2.4 on 2025-07-22 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0006_brainscanresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechassessmentresult',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='speechassessmentresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speechassessmentresult',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
